### ISSUE TITLE
"description".pluralize() -> "descriptia"

### ISSUE THREAD

**Issue by husnjak** [cesarferreira/kotlin-pluralizer#4]
should return "descriptions"
please fix this

**Comment by husnjak** [comment]
"collection".pluralize() -> "collectia"
should return "colections"

**Comment by husnjak** [comment]
"version".pluralize() -> "versia"
should be "versions"

**Comment by lephyrius** [comment]
I want to add:
"Person".pluralize() -> "Persa"
should be "People"
